on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # to verify the deployment originates from an appropriate
      pages: write # to deploy to Pages
      contents: read # to checkout private repositories

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      # If you don't have a build script, remove the following line
      - name: Build project
        run: npm run build

      - name: Archive artifact
        run: |
          mkdir -p dist
          # Copy only the necessary files to dist (assuming index.html is in the root)
          cp index.html ./dist
          # Compress the dist directory
          tar -czf dist.tar.gz ./dist

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: github-pages
          skip_cleanup: true # Skip cleanup to ensure HTML/CSS files are not removed
          publish_dir: ./dist # Specify the directory to deploy (only HTML and CSS)
