on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # to verify the deployment originates from an appropriate
      pages: write # to deploy to Pages
      contents: read # to checkout private repositories

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      # If you don't have a build script, remove the following line

      - name: Archive artifact
        run: |
          mkdir -p dist
          # Copy only the necessary files to dist (assuming index.html is in the root)
          cp index.html ./dist
          # Compress the dist directory
          tar -czf dist.tar.gz ./dist

      - name: Upload artifact (upgraded to v4)
        uses: actions/upload-artifact@v4
        with:
         name: github-pages
         path: ./dist

      - name: Deploy to GitHub Page
        uses: actions/deploy-pages@v4
        id: deployment

